# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

use_frameworks!

target 'AccordionView_Example' do
    pod 'AccordionView', :path => '../'

  target 'AccordionViewTests' do
    inherit! :search_paths
    pod 'FBSnapshotTestCase'
  end

end
